services:
  selenium-hub:
    image: selenium/hub:4.48.0-20260905
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.48.0-20260905
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
  firefox:
    image: selenium/node-firefox:4.48.0-20260905
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub